export default {
    emailField: 'input[id="email"]',
    passField: 'input[id="passwd"]',
    loginBtn: 'button[id="SubmitLogin"]',
    singInBtn: 'a[title="Log in to your customer account"]',
    searchInput: 'input[id="search_query_top"]',
    searchBtn: 'button.button-search',
    addToBasketBtn: 'a[title="View my shopping cart"]',
    addToBasketOnProductCartBtn: 'button.exclusive',
    checkbox: 'input[type="checkbox"]',
    womenCategory: 'a.sf-with-ul',
    dressesCategory: 'a.sf-with-ul',
    tshirtsCategory: 'a[title="T-shirts"]',
    categoryFilter: '[name="layered_category_4"]',
    sizeFilter: '[id="layered_id_attribute_group_1"]',
    colorFilter: '[id="layered_id_attribute_group_13"]',
    propertiesFilter: '[id="layered_id_feature_18"]',
    compositionsFilter: '[id="layered_id_feature_5"]',
    stylesFilter: '[id="layered_id_feature_11"]',
    avaibilityFilter: '[id="layered_quantity_1"]',
    conditionFilter: '[id="uniform-layered_condition_new"]',
    priceFilter: 'div[id="layered_price_slider"]',
    addToCartBtn: 'a[title="Add to cart"]',
    moreBtn: 'a[title="View"]',
    sortByBtn: 'select[id="selectProductSort"]',
    contShoppingBtn: '[title="Continue shopping"]',
    proceedBtn: 'a[title="Proceed to checkout"]',
    proceedBtn2: '.standard-checkout',
    proceedBtn3: 'button[name="processAddress"]',
    proceedBtn4: 'button[name="processCarrier"]',
    removeFromCartBtn: 'a.cart_quantity_delete',
    firstNameField: 'input[id="firstname"]',
    lastNameField: 'input[id="lastname"]',
    companyField: 'input[id="company"]',
    adressesField: 'input[id="address1"]',
    cityField: 'input[id="city"]',
    stateField: 'select[id="id_state"]',
    postCodefield: 'input[id="postcode"]',
    countryField: 'select[id="id_country"]',
    homePhoneField: 'input[id="phone"]',
    mobilePhoneField: 'input[id="phone_mobile"]',
    saveBtn: 'button[id="submitAddress"]',
    productCart: 'a.product_img_link',
    checkoutBtn: 'a[id="button_order_cart"]',
    deleteBtn: 'a.ajax_cart_block_remove_link',
    orderHistoryBtn: 'a[title="Orders"]',
    myAdressesBtn: 'a[title="Addresses"]',
    firstAdressesBtn: 'a[title="Add my first address"]',
    confirmBtn: 'button.button-medium',
    newsletterInput: 'input[id="newsletter-input"]',
    newsletterBtn: 'button[name="submitNewsletter"]',
    deleteAdressesBtn: 'a[title="Delete"]',
    selectProductBtn: 'select.form-control',
    sendCommentBtn: 'button[name="submitMessage"]',
    contactUsBtn: 'a[title="Contact us"]',
    enabledFilters: '[id="enabled_filters"]'
}